export default interface UserTecnogym {
    firstName: string,
    lastName: string,
    dateOfBirth: string,
    gender: string,
    email: string,
    externalId: string,
    address1?: string,
    zipCode?: string,
    city?: string,
    phoneNumber?: string,
    mobiliePhoneNumber?: string,
    stateProvince?: string,
    measurementSystem?: string,
}
